### ISSUE TITLE
API not working with filter

### ISSUE THREAD

**Issue by enpuliu** [jakehschwartz/finatra-swagger#21]
In the hello-sample, code  
filter[SampleFilter].getWithDoc("/courses/:courseId/student/:studentId")
doesn't work and server responds 404.
API cannot register with filter.

**Comment by kimxogus** [comment]
I'm having the same problem.

**Comment by jakehschwartz** [comment]
Thanks @enpuliu and @kimxogus , Ill look into this, but it probably won't be until the new year.

**Comment by andrerigon** [comment]
Same problem here - the route is not registered. For now, I extracted the endpoint to another controller and defined the filter when adding the controller. Thanks for looking at it!

**Comment by jakehschwartz** [comment]
Hey guys, quick update: my basement flooded this past weekend so I've been dealing with that. I will try to make time for this next weekend.

**Comment by jakehschwartz** [comment]
This should be fixed by https://github.com/jakehschwartz/finatra-swagger/pull/35 and will be in the 18.6.0 release

**Comment by kimxogus** [comment]
cool! when will 18.6.0 be released?

**Comment by jakehschwartz** [comment]
I published it to sonatype today so hopefully it's available tomorrow

**Comment by kimxogus** [comment]
Thanks 👍
BTW, can you push latest commits to repo?

**Comment by jakehschwartz** [comment]
Yeah, once the newest version is available, I'll push

**Comment by enpuliu** [comment]
It works for me now, thanks. Close the issue.

**Comment by kimxogus** [comment]
@jakehschwartz New release seems working, can you push?
btw, is there any specific reason not to push latest changes before maven release?
I made some changes and use in company's server as private module because maven release and git contents are different so I thought this is not maintained.

**Comment by jakehschwartz** [comment]
I pushed this morning. Sorry I forgot.

I think of the maven release as my deploy to production, so once my code is "in production", that is when it goes to master. If there is some kind of error in the release, because I have that automated, I don't want it to go to master and have people pull something with an error in it.

**Comment by kimxogus** [comment]
I understand, then can you checkout develop branch to push unstable latest changes?
I think it can help you to find issues before you publish in production

**Comment by jakehschwartz** [comment]
Yes I can. Laziness got the best of my last time.
