### ISSUE TITLE
Is it possible to support  com.twitter.finatra:finatra-http_2.11:2.16

### ISSUE THREAD

**Issue by chenhj** [jakehschwartz/finatra-swagger#22]
@jakehschwartz  

     Is it possible to support?
     com.twitter.finatra:finatra-http_2.11:2.16

      The use of "com.twitter", "finatra-http"% "2.11.0" in the current version, "com.twitter" and "finagle-mysql"%%% "6.45.0" also cited conflict

The use of "com.twitter", "finatra-http"% "2.11.0" in the current version, "com.twitter" and "finagle-mysql"%%% "6.45.0" also cited conflict
Can you make the changes?
"Com.twitter", "finatra-http"% "2.11.0" out
Modify to
"Org.apache.thrift"%, "libthrift",% "0.6.1"",
"Com.twitter.common"%, "metrics",% "0.0.39"",
"Org.slf4j"%, "slf4j-log4j12",% "1.7.16"",
"Com.twitter.finatra"%, "finatra-http_2.11",% "2.1.6"",
Release a new version and use it

**Comment by jakehschwartz** [comment]
Sorry @chenhj I don't plan on going back and supporting old versions of Scala and/or Finatra. Check out the [original repo](https://github.com/xiaodongw/swagger-finatra) to see if there is a version there that might suit your needs.

**Comment by chenhj** [comment]
@jakehschwartz thanks , There's nothing I need here
