### ISSUE TITLE
Support scala 2.11

### ISSUE THREAD

**Issue by ikhoon** [jakehschwartz/finatra-swagger#24]
Thank you in advance for maintaining finatra-swagger.
But I need different scala versions, 2.11 and 2.12.
So could you support scala 2.11? 🙂

**Comment by jakehschwartz** [comment]
The versions of finatra-swagger will be tied to the finatra version, and I think I'll only support the current and then the last 3 versions. At this point, all of these versions are only on Scala 2.12.

Checkout the old repository to older releases: https://github.com/xiaodongw/swagger-finatra
