### ISSUE TITLE
Any plan to support OpenAPI spec 3.0?

### ISSUE THREAD

**Issue by xcv58** [jakehschwartz/finatra-swagger#56]
We are using swagger-core 1.x (support only OpenAP spec 2.0) now and there are a bunch of useful features. For example, multiple hosts support:

> ## Can I specify multiple hosts, e.g. development, test and production?
> Multiple hosts are supported in OpenAPI 3.0. 2.0 supports only one host per API specification (or two if you count HTTP and HTTPS as different hosts). A possible way to target multiple hosts is to omit the host and schema from your specification and serve it from each host. In this case, each copy of the specification will target the corresponding host.

https://swagger.io/docs/specification/2-0/api-host-and-base-path/

The known blockers:

- `swagger-scala-module` doesn't support `swagger-core` 2.x: https://github.com/swagger-api/swagger-scala-module/issues/49#issuecomment-652847308

**Comment by mgd43b** [comment]
Hate to be the +1 but... 👍 

maybe it's possible to make use of https://github.com/swagger-akka-http/swagger-scala-module instead?

**Comment by jakehschwartz** [comment]
Yeah good thinking. I gave it a try tonight but get the swagger-core library upgraded. Will give it another try during the weekend if I get a chance. Or will accept PRs :)

**Comment by jakehschwartz** [comment]
@xcv58 @mgd43b Gave it a shot but having issues https://github.com/jakehschwartz/finatra-swagger/pull/70
