### ISSUE TITLE
Changelog 21.3 -> 21.4 / ComposedSchema support

### ISSUE THREAD

**Issue by gagbo** [jakehschwartz/finatra-swagger#73]
Hello,

First of all, thanks for your work on that converter, I am currently (trying to be) using it for an old project and it really seems to be the quickest way to get going :+1: 

My main issue (to avoid X/Y problem), is that I'd like to create a bodyParam for a `POST` endpoint that has a `oneOf` schema. I didn't find any easy Scala integration for now, so I'm resorting to calling Java directly to build a `io.swagger.v3.oas.models.media.ComposedSchema` and hopefully do the same logic as the bodyParam method of `FinatraOperation` to add the correct parameter with the new Schema. Without surprise I'm locked and I can't really understand how I can convert this `ComposedSchema` into a `Model` that it suitable for Swagger. Should I `new RefObject(schema.something ??)` ? I don't really know.

I'm currently working with 21.3.0 because I saw that it was the first version that bundles a swagger dependency recent enough to have the ComposedSchema : https://github.com/swagger-api/swagger-core/commit/9962469cb6b65c178f8e43172c54cd7c3041fff7 
But now I'm wondering 2 things: 

- What's the difference between 21.3 and 21.4, besides the Finatra bump ? I don't know if it could help my problem ?
- Do you have any idea (even blurry) about how I'd go to add `ComposedSchema` support to a (Request or Response) Model ? Through annotation or raw Java call or anything really. I'll probably try to implement that locally (maybe with an implicit like `SchemaUtil`) and then try to upstream it here if that's something that would be useful.

Regards,
Gerry

**Comment by jakehschwartz** [comment]
Hi Gerry @gagbo 

I believe from 21.3.0 to 21.4.0, I upgrade from Swagger V2 to the OpenAPI V3.

Unfortunately, I don't know what you are looking to do. Im not an expert in either Swagger or OpenAPI, I really only just migrated the codebase from one library to another.

I would happily accept any PR you can submit, as I don't have much time to support this anymore (I was doing this during work time but my role has changed over time.)

Let me know what you find and if there are other ways I can help
Jake

**Comment by gagbo** [comment]
Hello,

I was basically trying to generate a proper
```json
"TxView": {
        "type": "object",
        "oneOf": [
          {
            "$ref": "#/components/schemas/RippleTransactionView"
          },
          {
            "$ref": "#/components/schemas/BitcoinTransactionView"
          },
          {
            "$ref": "#/components/schemas/EthereumTransactionView"
          },
          {
            "$ref": "#/components/schemas/StellarTransactionView"
          }
        ]
      },
  ```
  from a 
  
```scala
sealed trait TxView {}
case class BitcoinTransactionView(...) extends TxView
case class EthereumTransactionView(...) extends TxView
case class RippleTransactionView(...) extends TxView
case class StellarTransactionView(...) extends TxView
```
structure, and passing `TxView` in either `ResponseWith` or `bodyParam` basically.

It turned out even when building the composed schema body parameter  manually (calling swagger-core classes directly to build models, that I add to `FinatraOperation`), swagger/openAPI didn't seem to generate the specification that I wanted.


For the record,
I ended up generating as much as I could this way, and then fixing the schema manually here and there, using [an online checker](https://apitools.dev/swagger-parser/online/) to make sure that my manual changes were compliant.

Thanks for your package anyway, it still saved me a lot of time (and taught me that swagger-core is quite messy :) )
