### ISSUE TITLE
allow users to remove the example_set_flag property

### ISSUE THREAD

**Issue by Zhen-hao** [jakehschwartz/finatra-swagger#80]
hi, I'm new to this library. 
I can't see from the code where `example_set_flag` is produced. 
Is it possible for the users to suppress the generation of this property? 

Thanks in advance!

**Comment by ndy2** [comment]
@jakehschwartz  Hi.

Can you consider using, `io.swagger.v2.core.util.Json.mapper()` in DocsController?
I found that it resolves #80, #82.

```scala
import io.swagger.v3.core.util.Json
import com.fasterxml.jackson.datatype.joda.JodaModule

private val objectMapper = Json.mapper()
    .registerModule(new JodaModule())
```

`Json.mapper()` is swagger oriented object mapper that can deserialize `OpenAPI` object.
It removes unnecessary `exampleSetFlag` and `items` or `types` properties in `swagger.json` and give us clean output.

ref. https://github.com/swagger-api/swagger-core/issues/4381
b.t.w. sorry for the short fix of previous PR. but I think this would be a better solution.
