### ISSUE TITLE
Version 23.x.x support

### ISSUE THREAD

**Issue by james-james-james** [jakehschwartz/finatra-swagger#81]
hello,
is there plan to release new versions supporting Finatra v23? as of now there is Finatra [23.11.0](https://mvnrepository.com/artifact/com.twitter/finatra-http-server_2.12/23.11.0).

thank you!
JH

**Comment by jakehschwartz** [comment]
@james-james-james I think I got it published this morning. I had to regenerate my keys, I had some issues with the previous version but it looks like its up in maven central. Let me know if there are any issues!

**Comment by james-james-james** [comment]
thank you for update.
I am still facing some routing issue, after opening http://localhost:8888/docs I am redirected to http://localhost:8888/docs/swagger-ui/4.18.2/index.html?url=/swagger.json

broken Swagger UI is rendered - missing styles/images and some default Swagger Petstore example is rendered
![image](https://github.com/jakehschwartz/finatra-swagger/assets/28301983/f829392b-a0b0-41ec-a92f-fee8fd1a10db)

http://localhost:8888/swagger.json looks good, populated correctly

**Comment by jakehschwartz** [comment]
@james-james-james I just published 23.11.1 to hopefully fix this. Looks like there was a change to the webjars implementation of Swagger that disabled the query params routing
