### ISSUE TITLE
ScalaObjectMapper for the endpoint '/swagger.json` should use lowerCamelCase Strategy

### ISSUE THREAD

**Issue by ndy2** [jakehschwartz/finatra-swagger#82]
Hi. I found there is a bug related to ScalaObjectMapper in DocsController

For below SwaggerModule with `termsOfService` and `SecurityRequirement`

```scala
object RealworldSwaggerModule extends SwaggerModule {

  @Singleton
  @Provides
  def openAPI: OpenAPI = {
    val openAPI = new OpenAPI()

    val info = new Info()
      .description("The Student / Course management API, this is a sample for swagger document generation")
      .version("1.0.1")
      .title("Student / Course Management API")
      .termsOfService("http://swagger.io/terms/")
      .contact(
        new Contact()
          .name("Swagger API Team")
          .url("http://swagger.io")
          .email("deukyun.nam@ahnlab.com")
      )
    openAPI
      .info(info)
      .addServersItem(new Server()
        .url("https://api.example.com/v1")
        .description("Production Server"))
      .components(
        new Components()
          .addSecuritySchemes(
            "sampleBasic",
            new SecurityScheme()
              .`type`(io.swagger.v3.oas.models.security.SecurityScheme.Type.HTTP)
              .scheme("basic")
          )
      )
      .addSecurityItem(new SecurityRequirement().addList("sampleBasic", "basic"))
  }
}
```

with sample Main code in below

```
class Realworld extends HttpServer {

  override val name: String                   = "SampleApp"

  override protected def modules: Seq[Module] = Seq(RealworldSwaggerModule)

  override def configureHttp(router: HttpRouter): Unit = {
    router
      .filter[CommonFilters]
      .add[DocsController]
      .add[SampleController]
  }
  override protected def disableAdminHttpServer: Boolean = true
  override protected def defaultHttpPort: String         = ":8080"
}

object RealworldMain extends Realworld
```

The Swagger UI does not shows `Terms of Service` & the `Authorize` button

![image](https://github.com/user-attachments/assets/ed0154c9-2a99-40c0-af0b-18f6fa30b3f4)

because what `DocsController` use is a default `ScalaObjectMapper` which gives snake_case converted `swagger.json` in endpoint `/swagger.json`

![image](https://github.com/user-attachments/assets/baa26e19-1128-4264-a942-3bdb1b9c7d61)
![image](https://github.com/user-attachments/assets/ab66cff0-c98f-4cd9-8964-ef860d5ef9b3)

They should be camelCased instead.

---

I found that by overriding default jackson module to use camel case by adding belows, it fixed

```scala
// for RealworldMain
override protected def jacksonModule: Module = RealworldObjectMapperModule

// add RealworldObjectMapperModule
object RealworldObjectMapperModule extends ScalaObjectMapperModule {
  override val propertyNamingStrategy: PropertyNamingStrategy = PropertyNamingStrategy.LOWER_CAMEL_CASE
}
```
![image](https://github.com/user-attachments/assets/57196b91-aedb-42da-9f14-5dd14cf401b3)

But it is not applicable for some use cases. (for me it is enough!)

---

I think fixing `DocsController`'s object mapper to lowerCamelCase strategy is quite reasonable solution for this problem
By the way, thank you for maintaining this great opensource with great usability.

**Comment by jakehschwartz** [comment]
Hi @ndy2 thanks for pointing this out. I don't think I will have time this week or next to look into this more, I might have some time around the holidays though. If you need a fix faster, Im happy to look at any Pull Requests.

My only hesitation is that this might change how the parameters in the requests are rendered, but I will check that with some of my projects when I test locally.

Thanks!
